/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GamePhase = { 'ended' : null } |
  { 'playing' : null } |
  { 'waiting' : null };
export interface GameRoomView {
  'id' : bigint,
  'name' : string,
  'players' : Array<PlayerView>,
  'winningTeam' : [] | [Team],
  'phase' : GamePhase,
  'blueTeamKills' : bigint,
  'redTeamKills' : bigint,
}
export interface PlayerView {
  'id' : Principal,
  'jumping' : boolean,
  'crouching' : boolean,
  'name' : [] | [string],
  'coins' : bigint,
  'team' : Team,
  'isAlive' : boolean,
  'position' : Position,
  'kills' : bigint,
}
export interface Position { 'x' : number, 'y' : number }
export type Team = { 'red' : null } |
  { 'blue' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRoomState' : ActorMethod<[bigint], GameRoomView>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[bigint, [] | [string], Team], undefined>,
  'listRooms' : ActorMethod<[], Array<GameRoomView>>,
  'movePlayer' : ActorMethod<[bigint, Position, boolean, boolean], undefined>,
  'reload' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shoot' : ActorMethod<[bigint, Principal], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];