/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Team = IDL.Variant({ 'red' : IDL.Null, 'blue' : IDL.Null });
export const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const PlayerView = IDL.Record({
  'id' : IDL.Principal,
  'jumping' : IDL.Bool,
  'crouching' : IDL.Bool,
  'name' : IDL.Opt(IDL.Text),
  'coins' : IDL.Nat,
  'team' : Team,
  'isAlive' : IDL.Bool,
  'position' : Position,
  'kills' : IDL.Nat,
});
export const GamePhase = IDL.Variant({
  'ended' : IDL.Null,
  'playing' : IDL.Null,
  'waiting' : IDL.Null,
});
export const GameRoomView = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'players' : IDL.Vec(PlayerView),
  'winningTeam' : IDL.Opt(Team),
  'phase' : GamePhase,
  'blueTeamKills' : IDL.Nat,
  'redTeamKills' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRoomState' : IDL.Func([IDL.Nat], [GameRoomView], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), Team], [], []),
  'listRooms' : IDL.Func([], [IDL.Vec(GameRoomView)], ['query']),
  'movePlayer' : IDL.Func([IDL.Nat, Position, IDL.Bool, IDL.Bool], [], []),
  'reload' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shoot' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Team = IDL.Variant({ 'red' : IDL.Null, 'blue' : IDL.Null });
  const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const PlayerView = IDL.Record({
    'id' : IDL.Principal,
    'jumping' : IDL.Bool,
    'crouching' : IDL.Bool,
    'name' : IDL.Opt(IDL.Text),
    'coins' : IDL.Nat,
    'team' : Team,
    'isAlive' : IDL.Bool,
    'position' : Position,
    'kills' : IDL.Nat,
  });
  const GamePhase = IDL.Variant({
    'ended' : IDL.Null,
    'playing' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const GameRoomView = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'players' : IDL.Vec(PlayerView),
    'winningTeam' : IDL.Opt(Team),
    'phase' : GamePhase,
    'blueTeamKills' : IDL.Nat,
    'redTeamKills' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRoomState' : IDL.Func([IDL.Nat], [GameRoomView], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), Team], [], []),
    'listRooms' : IDL.Func([], [IDL.Vec(GameRoomView)], ['query']),
    'movePlayer' : IDL.Func([IDL.Nat, Position, IDL.Bool, IDL.Bool], [], []),
    'reload' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shoot' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };